import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { DEFAULT_PROFILE_GALLERY, validateProfileGallery } from '../shared/profileGallery.ts';
import { COSMETICS } from '../server/src/shopCatalog.ts';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const browser = await chromium.launch({channel:'msedge',headless:true});
const out=resolve(process.env.QA_OUTPUT ?? '.impeccable/review/profile'); await mkdir(out,{recursive:true});
try {
  const page=await browser.newPage({viewport:{width:1536,height:1024}});
  const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  let user={id:999,email:'preview@example.invalid',display_name:'Test player',diceTheme:'white',profileStyle:'astral',bio:'',pronouns:'they/them',avatarPath:'',profileGallery:{...DEFAULT_PROFILE_GALLERY}};
  let failSave=false, writes=0;
  const badges=[{id:'first-campaign',name:'The Adventure Begins',description:'A first campaign.',badgeImage:'/assets/achievements/first-campaign-384.webp'}];
  await page.addInitScript(()=>sessionStorage.setItem('vivid-realms-entrance-v1','seen'));
  await page.route('**/socket.io/**',r=>r.abort());
  await page.route('**/uploads/qa.webp',r=>r.fulfill({path:resolve('client/public/assets/profile-gallery/example/banner.webp'),contentType:'image/webp'}));
  await page.route('**/api/**', async r=>{
    const path=new URL(r.request().url()).pathname,method=r.request().method();
    if(path==='/api/auth/me') return r.fulfill({json:{user}});
    if(path==='/api/achievements/profiles/999') return r.fulfill({json:{profile:user,showcase:badges,characters:[],campaigns:[]}});
    if(path.startsWith('/api/achievements/profiles/')) return r.fulfill({status:404,json:{error:'Profile not found.'}});
    if(path==='/api/achievements') return r.fulfill({json:{achievements:[],showcase:badges}});
    if(path==='/api/shop') return r.fulfill({json:{items:COSMETICS.map(i=>({...i,owned:i.rarity==='starter'})),equipped:{},ownedDiceThemes:[],wallet:{balance:0,bypass:false},bundles:[]}});
    if(path==='/api/auth/me/dice-presets') return r.fulfill({json:{presets:[]}});
    if(path==='/api/uploads/image') return r.fulfill({json:{url:'/uploads/qa.webp'}});
    if(path==='/api/auth/me/profile' && method==='PUT') {
      writes++;
      if(failSave) return r.fulfill({status:500,json:{error:'Synthetic save failure'}});
      const body=r.request().postDataJSON();
      user={...user,display_name:body.displayName,pronouns:body.pronouns,bio:body.bio,avatarPath:body.avatarPath,profileGallery:validateProfileGallery(body.profileGallery)};
      return r.fulfill({json:{user}});
    }
    return r.fulfill({json:{}});
  });
  const root=process.env.QA_URL ?? 'http://127.0.0.1:5182';
  const capture=async(name:string)=>{
    await page.evaluate(async()=>{await document.fonts.ready; await Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.onload=resolve;img.onerror=resolve;}))); window.scrollTo({top:0,behavior:'instant'});});
    await page.screenshot({path:`${out}/${name}.png`,fullPage:true});
  };
  await page.goto(root+'/profiles/example');
  await page.getByRole('heading',{name:'Ruby Rose',exact:true}).waitFor();
  await capture('example-desktop');
  assert.equal(await page.locator('.pg-main img').evaluateAll(imgs=>imgs.every(i=>(i as HTMLImageElement).naturalWidth>0)),true);
  assert.equal(writes,0,'example must not modify an account');
  await page.locator('.pg-rail').getByRole('link',{name:'Make yours'}).click();
  await page.getByRole('heading',{name:'Test player',exact:true}).waitFor();
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByLabel('Bio',{exact:false}).fill('A gallery I made myself.');
  await page.getByRole('button',{name:'Cover art',exact:true}).click();
  assert.equal(await page.locator('.pg-banner-picker button').count(),4);
  await page.getByRole('button',{name:'Lakeside Citadel',exact:true}).click();
  assert.ok((await page.locator('.pg-banner img').getAttribute('src'))?.endsWith('/banner.webp'));
  await page.getByRole('button',{name:'Midnight',exact:true}).click();
  await page.locator('.pg-banner > .pg-banner-midnight').waitFor();
  await capture('banner-picker');
  assert.equal(await page.locator('.pg-panel').evaluate(el=>getComputedStyle(el).getPropertyValue('--pg-text').trim()),'#efe9df');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:'Done editing',exact:true}).click();
  await page.getByText('Your gallery is saved.',{exact:true}).waitFor();
  assert.equal(user.profileGallery.coverPath,'preset:midnight');
  await page.reload(); await page.locator('.pg-banner-midnight').waitFor();
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByRole('button',{name:'Cover art',exact:true}).click();
  await page.locator('.pg-panel input[type=file]').setInputFiles({name:'sample.webp',mimeType:'image/webp',buffer:await readFile('client/public/assets/profile-gallery/example/banner.webp')});
  await page.locator('.pg-panel img.pg-thumb').waitFor();
  await page.getByRole('button',{name:'Done editing',exact:true}).click(); await page.getByText('Your gallery is saved.',{exact:true}).waitFor();
  assert.equal(user.profileGallery.coverPath,'/uploads/qa.webp');
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByRole('button',{name:'Cover art',exact:true}).click();
  await page.getByRole('button',{name:'Forest',exact:true}).click();
  const before=writes; await page.getByRole('button',{name:'Preview',exact:true}).click();
  assert.equal(await page.locator('.pg-panel').count(),0); assert.equal(writes,before);
  await page.getByRole('button',{name:'Exit preview',exact:true}).click();
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Customize',exact:true}).click();
  await page.goBack(); await page.locator('.pg-banner-forest').waitFor();
  await page.getByRole('button',{name:'Discard changes',exact:true}).click();
  assert.equal(await page.locator('.pg-banner img').getAttribute('src'),'/uploads/qa.webp');
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByRole('button',{name:'Layout',exact:true}).click();
  await page.getByLabel('My character',{exact:true}).uncheck();
  await page.getByRole('button',{name:'Done editing',exact:true}).click(); await page.getByText('Your gallery is saved.',{exact:true}).waitFor();
  assert.ok(!user.profileGallery.sections.includes('character'));
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Edit profile',exact:true}).click();
  await page.getByRole('button',{name:'Cover art',exact:true}).click();
  await page.getByRole('button',{name:'Ember',exact:true}).click();
  await capture('mobile-editor');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  failSave=true; await page.getByRole('button',{name:'Done editing',exact:true}).click(); await page.getByRole('alert').filter({hasText:'Synthetic save failure'}).waitFor();
  failSave=false; await page.getByRole('button',{name:'Done editing',exact:true}).click(); await page.getByText('Your gallery is saved.',{exact:true}).waitFor();
  assert.equal(user.profileGallery.coverPath,'preset:ember');
  await capture('mobile-owner');
  await page.goto(root+'/profiles/999'); await page.getByRole('heading',{name:'Test player',exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Edit profile',exact:true}).count(),0);
  await page.goto(root+'/profiles/example'); await page.getByRole('heading',{name:'Ruby Rose',exact:true}).waitFor(); await capture('example-mobile');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.goto(root+'/profiles/123'); await page.getByRole('alert').waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: demo assets, built-in banner preview/save/reload, upload, preview without publishing, draft recovery, discard, layout, mobile editor, failed-save recovery, visitor controls, private-profile error; no runtime errors.');
} finally { await browser.close(); }
